#!/bin/bash

# Update system packages
sudo apt update

# Install Nginx
sudo apt install nginx -y

# Start Nginx service
sudo service nginx start

# Enable Nginx to start on boot
sudo systemctl enable nginx

# Display Nginx status
sudo service nginx status

